azp-builder_2.5

diff --git a/usr/bin/azp-builder b/usr/bin/azp-builder
--- a/usr/bin/azp-builder
+++ b/usr/bin/azp-builder
@@ -1,19 +1,20 @@
 #!/bin/bash
 
-### AZP Builder 1.5
+### AZP Builder 2.5
 # AZP Offical Site: https://azp-paket-sistemi.github.io
 # AZP Offical Depo: https://azp-paket-sistemi.github.io/azp-depo
 
-# 2022 AZP
-# 2019-2022 PacPERRO OS
+# © 2021-2023 AZP
+# © 2019-2023 PacPERRO
 
 # Tərcümə faylı
 TEXTDOMAINDIR=/usr/share/locale
 TEXTDOMAIN=azp-builder
 
-# Bəzi teglər :)
+# Rənglər
 error=$(echo -e "\033[1;31m E: \033[:0m")
 process=$(echo -e "\033[1;34m P: \033[:0m")
+info=$(echo -e "\033[1;36m I: \033[:0m")
 finished=$(echo -e "\033[1;32m F: \033[:0m")
 
 depends="zip tar"
@@ -21,52 +22,254 @@ for d in ${depends};
 do
   if ! command -v "${d}" &>/dev/null; then
     echo "$error" "${d}" $" -- not installed !"
-    exit
+    exit 1
   fi
 done
 
-echo -e "\033[1;32m AZP Package Builder \033[:0m"
-sleep 0.3
-
-if [[ $1 == "--build" ]]
+if [[ "$1" == "" ]]
 then
-  if ! [[ "$2" != "" ]]
+  echo -e "\033[1;32m |-- AZP Builder -- 2.5 --| \033[:0m"
+  echo "-----------------------------------------"
+  echo -e "\033[1;36m Yardım: -h \033[:0m"
+  echo -e "\033[1;36m Help: -h \033[:0m"
+  echo "-----------------------------------------"
+  sleep 0.3
+fi
+
+# Paket Yığma
+if [[ "$1" == "-build" ]]
+then
+  datafolder=$2
+  [[ "$datafolder" == "" ]] && echo "$error" $"The project folder was not selected !" && exit 1
+  [[ ! -d $datafolder ]] && echo "$error" $"Project folder not found !" && exit 1
+  cd $datafolder
+  [[ ! -d azpsrc ]] && echo "$error" $"'azpsrc' folder not found !" && exit 1
+  if [[ ! -f azp_data ]] 
   then
-    echo "$error" $"The project folder was not selected !"
-    exit
+    echo "$error" $"'azp_data' data file not found !"
+    exit 1
   fi
-  if ! [ -d $2 ]
-  then
-    exit
-  fi
-  project=$2
-  cd $project
-  tar -cvjSf src.tar.bz2 * &>/dev/null
-  for src in $(ls -d *);
-  do
-    [[ -d ${src} ]] && rm -r ${src}
-  done
-  read -p $"Do you want a add the depends ? [h/y]: " dp_add
-  if [ $dp_add == "h" ]
-  then
-    read -p "Depends: " d
-    for dep in $d;
-    do
-      echo "${dep}" >> depends
-    done
-  fi
-  read -p $"App Name: " app_name
-  read -p $"App Version: " app_version
-  read -p $"App Description: " app_description
-  read -p $"App Maintainer: " app_maintainer
+  app_name=$(sed -n 1p azp_data)
+  app_description=$(sed -n 2p azp_data)
+  app_version=$(sed -n 3p azp_data)
+  app_maintainer=$(sed -n 4p azp_data)
+  app_architecture=$(sed -n 5p azp_data)
+  echo "$process" $"Create 'src.tar.bz2' package..."
+  cd azpsrc
+  tar -cvjSf ../src.tar.bz2 * &>/dev/null
+  # md5sum yazdırma
+  echo "$(find . -type f -exec md5sum {} + | LC_ALL=C sort)" >> ../src_md5sum
+  cd ..
+  rm -r azpsrc
   sleep 0.2
-  echo "$app_name" >> app-name
-  echo "name: $app_name" >> info
-  echo "description: $app_description" >> info
-  echo "version: $app_version" >> info
-  echo "maintainer: $app_maintainer" >> info
-   [[ $app_description == "*" ]] && read -p $"description file: " dfi && more_description=$(cat $dfi) && echo "description: $more_description" >> info
+  echo "$process" $"Write data..."
+  echo "${app_name:6}" >> app-name
+  echo "name: ${app_name:6}" >> info
+  if [[ "${app_description:12}" == "*" ]]
+  then
+    echo "description: *" >> info
+    description=$(sed -n 6,1000p azp_data)
+    longdescription="description:${description:12}"
+  else
+    echo "description:${app_description:12}" >> info
+  fi
+  echo "version: ${app_version:9}" >> info
+  echo "maintainer: ${app_maintainer:12}" >> info
+  echo "architecture: ${app_architecture:14}" >> info
+  printf "$longdescription" >> info
+  rm -r azp_data
   echo "$process" $"Package build..."
-  zip -r ../$app_name-$app_version.azp * &>/dev/null
-  echo "$finished" "$app_name-$app_version.azp " $"build finished"
+  build_package_name=''${app_name:6}'_'${app_version:9}'.azp'
+  zip ../"$build_package_name" *
+  echo "$finished" "$build_package_name" $"== build finished"
+fi
+
+
+
+# 'azp-data' düzəltmə
+if [[ "$1" == "-create-data" ]]
+then
+  datafolder=$2
+  if [[ ! -d $datafolder ]]
+  then
+    echo "$error" $"Source folder not found !"
+    exit 1
+  fi
+  cd $datafolder
+  for files in { azp_data preins postins prerm postrm };
+  do
+    if [ -f "${files}" ]
+    then
+      echo "$info" "${files}" $"avaliable"
+      exit
+    fi
+  done
+  echo "$process" $"Create data files..."
+  echo "$process" $"Create 'azp_data'..."
+  touch azp_data
+  echo "$process" $"Create 'depends'..."
+  touch depends
+  echo "$process" $"Create 'preins'..."
+  touch preins
+  chmod u+x preins
+  echo "$process" $"Create 'postins'..."
+  touch postins
+  chmod u+x postins
+  echo "$process" $"Create 'prerm'..."
+  touch prerm
+  chmod u+x prerm
+  echo "$process" $"Create 'postrm'..."
+  touch postrm
+  chmod u+x postrm
+  echo "$process" $"Write data..."
+  echo """name:
+description:
+version:
+maintainer:
+architecture:
+description:""" >> azp_data
+  echo "$finished" $"Process finished"
+fi
+
+
+
+# 'azpsrc' mənbə qovluğunu hazırlama
+if [[ "$1" == "-create-azpsrc" ]]
+then
+  datafolder=$2
+  [[ "$datafolder" == "" ]] && echo "$error" $"The project folder was not selected !" && exit 1
+  [[ ! -d $datafolder ]] && echo "$error" $"Project folder not found !" && exit 1
+  cd $datafolder
+  echo "$process" $"Create 'azpbuild' script file..."
+  for files in { azpbuild azpdepends_x preins postins prerm postrm };
+  do
+    if [ -f "${files}" ]
+    then
+      echo "$info" "${files}" $"avaliable"
+      exit
+    fi
+  done
+  touch azpbuild
+  chmod u+x azpbuild
+  echo '''#!/bin/bash
+# AZP mənbə yığma skript faylı
+# AZP source build script file
+
+name=""
+release=""
+version=""
+maintainer=""
+url=""
+arch=()
+source=()
+depends=()
+package=""
+packtype=""
+description=""""""
+
+setup() {
+
+}
+
+build() {
+
+}
+
+package() {
+
+}
+
+config() {
+
+}
+'''  >> azpbuild
+  echo "$process" $"Create 'preins'..."
+  touch preins
+  chmod u+x preins
+  echo "$process" $"Create 'postins'..."
+  touch postins
+  chmod u+x postins
+  echo "$process" $"Create 'prerm'..."
+  touch prerm
+  chmod u+x prerm
+  echo "$process" $"Create 'postrm'..."
+  touch postrm
+  chmod u+x postrm
+  echo "$process" $"Create 'azpdepends_x'..."
+  touch azpdepends_x
+  chmod u+x azpdepends_x
+  echo "$(cat azpbuild)" >> azpdepends_x
+  echo "$finished" $"Process finished"
+fi
+
+
+
+# 'azpsh' skript faylını hazırlama
+if [[ "$1" == "-create-azpsh" ]]
+then
+  scriptname=$2
+  [[ "$datafolder" != "" ]] && echo "$error" $"Script file was not selected !" && exit 1
+  echo "$process" "$scriptname.azpsh" $"== create script file..."
+  touch $scriptname.azpsh
+  chmod u+x $scriptname.azpsh
+  echo '''#!/bin/bash
+# AZP mənbə yığma skript faylı
+# AZP source build script file
+
+name=""
+release=""
+version=""
+maintainer=""
+url=""
+arch=()
+source=()
+package=""
+packtype=""
+description=""""""
+
+setup() {
+
+}
+
+build() {
+
+}
+
+package() {
+
+}
+
+config() {
+
+}
+'''  >> $scriptname.azpsh
+  echo "$finished" $"Process finished"
+fi
+
+
+
+# 'azpsrc' mənbə qovluğunu yığma
+if [[ "$1" == "-build-azpsrc" ]]
+then
+  datafolder=$2
+  [[ "$datafolder" == "" ]] && echo "$error" $"The project folder was not selected !" && exit 1
+  [[ ! -d $datafolder ]] && echo "$error" $"Project folder not found !" && exit 1
+  cd $datafolder
+  [[ ! -f azpbuild ]] && echo "$error" $"'azpbuild' script file not found !" && exit 1
+  echo "$process" $"Package build..."
+  source azpbuild &>/dev/null
+  build_package_name=''$name'_'$version'.azpsrc'
+  zip ../"$build_package_name" *
+  echo "$finished" "$build_package_name" $"== build finished"
+fi
+
+# Yardım
+if [[ "$1" == "-h" ]]
+then
+  echo "$info" "<< AZP Builder -- 2.5 >>"
+  echo "$info" "azp-builder -build [folder]" $"== Build AZP package"
+  echo "$info" "azp-builder -build-azpsrc [folder]" $"== Build .azpsrc source package"
+  echo "$info" "azp-builder -create-data [folder]" $"== Create 'azp_data' data file"
+  echo "$info" "azp-builder -create-azpsrc [folder]" $"== Create .azpsrc source package"
+  echo "$info" "azp-builder -create-azpsh [name]" $"== Create .azpsh source script"
 fi
